@Library("my-libraries") _
pipeline {
    agent{
        label 'server'
    }
    stages {
        stage('compile cpp file') {
            steps {
                myString()
                
                
            }
        }
   }
}
